{% set version = "0.0.1" %}

package:
  name: cedar-datacube
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/24/14/7dc25dea5a4410a66075155ab949e063d8ae31e2c5be103279507f8a2a76/cedar-datacube-{{ version }}.tar.gz
  sha256: a3925be0a01fe906d354d9e1a32a18f5075c3be3acb8059a2f46b90dc6728a96

build:
  number: 0
  skip: true  # [py<36]
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - stems =0.0.2
    - dask
    - distributed
    - numpy
    - pandas
    - xarray
    - cytoolz
    - toolz
    - pyyaml
    - jsonschema
    - pyyaml
    - earthengine-api
    - google-api-core
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - google-cloud-storage
    - click
    - click-plugins
    - cligj

test:
  imports:
    - cedar
    - cedar.config
    - cedar.metadata
    - cedar.ordering
    - cedar.stores.gdrive
    - cedar.stores.gcs
  command:
    - cedar --help

about:
  home: https://github.com/ceholden/cedar-datacube
  license: BSD-3-Clause
  license_file: LICENSE
