{% set version = "0.0.2.post0" %}

package:
  name: cedar-datacube
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/14/56/226d5e74cca83c14d80b9e3be43cc4b27d4a4387b7f46e7159c9631f682a/cedar-datacube-0.0.2.post0.tar.gz
  sha256: e823c7761b5be66032b07a00e00b54932f03044b8e7d76181f26b437af0cb865

build:
  number: 0
  skip: true  # [py<36]
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - stems =0.0.2.post0
    - dask
    - distributed
    - numpy
    - pandas
    - xarray
    - cytoolz
    - toolz
    - pyyaml
    - jsonschema
    - pyyaml
    - earthengine-api
    - google-api-core
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - google-cloud-storage
    - click
    - click-plugins
    - cligj

test:
  imports:
    - cedar
    - cedar.config
    - cedar.metadata
    - cedar.ordering
    - cedar.stores.gdrive
    - cedar.stores.gcs
  command:
    - cedar --help

about:
  home: https://github.com/ceholden/cedar-datacube
  license: BSD-3-Clause
  license_file: LICENSE
  licence_family: BSD
  summary: 'Create Earth engine Data cubes of Analytical Readiness'
  description: |
    cedar is a library and application to help download and preprocess
    satellite data to be “analysis ready data” (ARD) “data cube” as quickly as
    possible. cedar has been designed primarily to preprocess Landsat data, and
    can help acquire data from the Google Earth Engine (GEE). It is based on
    tools within the Python ecosystem for geospatial data processing
    (rasterio), saving and working with N-dimensional data (netCDF4 and
    xarray), and parallelization (dask and distributed).
